from .sms_region_helper import *


DELFINO_PLAZA: SmsRegion = SmsRegion(SmsRegionName.PLAZA,
    [Requirements(location=SmsRegionName.AIRSTRIP + " - Delfino Airstrip Dilemma")],
    shines=[Shine("Shine Sprite in the Sand", [Requirements(HOVORSHI)]),
        Shine("Clean the West Bell", [Requirements(ANY_SPLASHER)]),
        Shine("Super Slide", [Requirements(ROCKET_OR_HOVER_OR_YOSHI)]),
        Shine("Turbo Dash!", [Requirements([[NozzleType.turbo]])]),
        Shine("Lighthouse Roof", [Requirements([[NozzleType.rocket]])]),
        Shine("Clean the East Bell", [Requirements(ROCKET_AND_SPLASHER)]),
        Shine("Shine Gate", [Requirements(ROCKET_AND_SPLASHER)]),
        Shine("Lily Pad Ride", [Requirements(ALL_SPLASHER)]),
        Shine("Turbo Track", [Requirements([[NozzleType.turbo]])]),
        Shine("Red Coin Field", [Requirements(ROCKET_OR_HOVER_AND_SPRAY)]),

        Shine("Pachinko Game", [Requirements([[NozzleType.hover, NozzleType.rocket]]),
            Requirements([[NozzleType.hover]], shines=3),
            Requirements([[NozzleType.hover]], skip_forward=True)]),
        Shine("The Gold Bird", [Requirements(SPROVER_OR_YOSHI, shines=10),
            Requirements(SPROVER_OR_YOSHI, skip_forward=True)]),
        Shine("Boxing Clever 1", [Requirements(ANY_SPLASHER),
            Requirements(skip_forward=True)]),
        Shine("Boxing Clever 2", [Requirements(ANY_SPLASHER),
            Requirements(skip_forward=True)]),
        Shine("Chuckster", [Requirements(ANY_SPLASHER),
            Requirements(skip_forward=True)]),
        Shine("100 Coins", [Requirements(ROCKET_OR_HOVER),
            Requirements(skip_forward=True)], hundred=True)],

    blue_coins=[BlueCoin("Turbo Pillar", [Requirements([[NozzleType.turbo]])]),
        BlueCoin("Burning Pianta", [Requirements(ANY_SPLASHER)]),
        BlueCoin("Shine Gate M", [Requirements(ANY_SPLASHER)]),
        BlueCoin("Tower M", [Requirements(ANY_SPLASHER)]),
        BlueCoin("Chuckster Room M", [Requirements(ANY_SPLASHER)]),
        BlueCoin("Sea Sewer"),
        BlueCoin("Tower Yellow Goo", [Requirements([[NozzleType.yoshi]])]),
        BlueCoin("Jail Cell"),
        BlueCoin("Police Station Yellow Goo", [Requirements([[NozzleType.yoshi]])]),
        BlueCoin("Shine Gate Sewer"),
        BlueCoin("Canal Sewer"),
        BlueCoin("Blue Bird Near Sirena Pipe", [Requirements(SPRAY_OR_YOSHI)]),
        BlueCoin("Blue Bird Near Crate Guy", [Requirements(SPRAY_OR_YOSHI)]),
        BlueCoin("Statue X", [Requirements(ANY_SPLASHER)]),
        BlueCoin("Bell Tower X", [Requirements(ANY_SPLASHER)]),
        BlueCoin("Pineapple Basket", [Requirements(ANY_SPLASHER),
          Requirements(skip_forward=True)]),
        BlueCoin("Durian Basket", [Requirements(ANY_SPLASHER),
          Requirements(skip_forward=True)]),
        BlueCoin("Banana Basket", [Requirements(ANY_SPLASHER),
          Requirements(skip_forward=True)]),
        BlueCoin("Coconut Basket", [Requirements(ANY_SPLASHER)])],

    # NozzleBox("Shadow Mario Yoshi Egg Chase", 523911, Requirements([NozzleType.spray], location="Pinna Park - The Wilted Sunflowers")),
    # NozzleBox("Shadow Mario Rocket Nozzle Chase", 523870, Requirements([NozzleType.splasher, NozzleType.yoshi], shines=30)),
    # NozzleBox("Shadow Mario Turbo Nozzle Chase", 523871, Requirements([NozzleType.splasher, NozzleType.yoshi], shines=25)),
    parent_region=SmsRegionName.AIRSTRIP)

BOATHOUSE_TRADERS: SmsRegion = SmsRegion(SmsRegionName.BOATHOUSE,
    requirements=[Requirements(shines=3)],
    shines=[Shine("Shine 1", [Requirements(blue_coins=10)]),
        Shine("Shine 2", [Requirements(blue_coins=20)]),
        Shine("Shine 3", [Requirements(blue_coins=30)]),
        Shine("Shine 4", [Requirements(blue_coins=40)]),
        Shine("Shine 5", [Requirements(blue_coins=50)]),
        Shine("Shine 6", [Requirements(blue_coins=60)]),
        Shine("Shine 7", [Requirements(blue_coins=70)]),
        Shine("Shine 8", [Requirements(blue_coins=80)]),
        Shine("Shine 9", [Requirements(blue_coins=90)]),
        Shine("Shine 10", [Requirements(blue_coins=100)]),
        Shine("Shine 11", [Requirements(blue_coins=110)]),
        Shine("Shine 12", [Requirements(blue_coins=120)]),
        Shine("Shine 13", [Requirements(blue_coins=130)]),
        Shine("Shine 14", [Requirements(blue_coins=140)]),
        Shine("Shine 15", [Requirements(blue_coins=150)]),
        Shine("Shine 16", [Requirements(blue_coins=160)]),
        Shine("Shine 17", [Requirements(blue_coins=170)]),
        Shine("Shine 18", [Requirements(blue_coins=180)]),
        Shine("Shine 19", [Requirements(blue_coins=190)]),
        Shine("Shine 20", [Requirements(blue_coins=200)]),
        Shine("Shine 21", [Requirements(blue_coins=210)]),
        Shine("Shine 22", [Requirements(blue_coins=220)]),
        Shine("Shine 23", [Requirements(blue_coins=230)]),
        Shine("Shine 24", [Requirements(blue_coins=240)]),
    ], trade=True, parent_region=SmsRegionName.PLAZA)