from .sms_region_helper import *


DELFINO_PLAZA: SmsRegion = SmsRegion(SmsRegionName.PLAZA,
    [Requirements(location=SmsRegionName.AIRSTRIP + " - Delfino Airstrip Dilemma")],
    shines=[Shine("Shine Sprite in the Sand", 523117, [Requirements(HOVORSHI)]),
        Shine("Clean the West Bell", 523096, [Requirements(ANY_SPLASHER)]),
        Shine("Super Slide", 523090, [Requirements(ROCKET_OR_HOVER_OR_YOSHI)]),
        Shine("Turbo Dash!", 523116, [Requirements([[NozzleType.turbo]])]),
        Shine("Lighthouse Roof", 523093, [Requirements([[NozzleType.rocket]])]),
        Shine("Clean the East Bell", 523097, [Requirements(ROCKET_AND_SPLASHER)]),
        Shine("Shine Gate", 523099, [Requirements(ROCKET_AND_SPLASHER)]),
        Shine("Lily Pad Ride", 523091, [Requirements(ALL_SPLASHER)]),
        Shine("Turbo Track", 523087, [Requirements([[NozzleType.turbo]])]),
        Shine("Red Coin Field", 523092, [Requirements(ROCKET_OR_HOVER_AND_SPRAY)]),

        Shine("Pachinko Game", 523089, [Requirements([[NozzleType.hover, NozzleType.rocket]]),
            Requirements([[NozzleType.hover]], shines=3),
            Requirements([[NozzleType.hover]], skip_forward=True)]),
        Shine("The Gold Bird", 523118, [Requirements(SPROVER_OR_YOSHI, shines=10),
            Requirements(SPROVER_OR_YOSHI, skip_forward=True)]),
        Shine("Boxing Clever 1", 523094, [Requirements(ANY_SPLASHER),
            Requirements(skip_forward=True)]),
        Shine("Boxing Clever 2", 523095, [Requirements(ANY_SPLASHER),
            Requirements(skip_forward=True)]),
        Shine("Chuckster", 523098, [Requirements(ANY_SPLASHER),
            Requirements(skip_forward=True)]),
        Shine("100 Coins", 523107, [Requirements(ROCKET_OR_HOVER),
            Requirements(skip_forward=True)], hundred=True)],

    blue_coins=[BlueCoin("Turbo Pillar", 523121, [Requirements([[NozzleType.turbo]])]),
          BlueCoin("Burning Pianta", 523124, [Requirements(ANY_SPLASHER)]),
          BlueCoin("Shine Gate M", 523125, [Requirements(ANY_SPLASHER)]),
          BlueCoin("Tower M", 523126, [Requirements(ANY_SPLASHER)]),
          BlueCoin("Chuckster Room M", 523127, [Requirements(ANY_SPLASHER)]),
          BlueCoin("Sea Sewer", 523132),
          BlueCoin("Tower Yellow Goo", 523133, [Requirements([[NozzleType.yoshi]])]),
          BlueCoin("Jail Cell", 523134),
          BlueCoin("Police Station Yellow Goo", 523135, [Requirements([[NozzleType.yoshi]])]),
          BlueCoin("Shine Gate Sewer", 523136),
          BlueCoin("Canal Sewer", 523137),
          BlueCoin("Blue Bird Near Sirena Pipe", 523138, [Requirements(SPRAY_OR_YOSHI)]),
          BlueCoin("Blue Bird Near Crate Guy", 523139, [Requirements(SPRAY_OR_YOSHI)]),
          BlueCoin("Statue X", 523122, [Requirements(ANY_SPLASHER)]),
          BlueCoin("Bell Tower X", 523123, [Requirements(ANY_SPLASHER)]),
          BlueCoin("Pineapple Basket", 523128, [Requirements(ANY_SPLASHER),
              Requirements(skip_forward=True)]),
          BlueCoin("Durian Basket", 523129, [Requirements(ANY_SPLASHER),
              Requirements(skip_forward=True)]),
          BlueCoin("Banana Basket", 523130, [Requirements(ANY_SPLASHER),
              Requirements(skip_forward=True)]),
          BlueCoin("Coconut Basket", 523131, [Requirements(ANY_SPLASHER)])],

          # NozzleBox("Shadow Mario Yoshi Egg Chase", 523911, Requirements([NozzleType.spray], location="Pinna Park - The Wilted Sunflowers")),
          # NozzleBox("Shadow Mario Rocket Nozzle Chase", 523870, Requirements([NozzleType.splasher, NozzleType.yoshi], shines=30)),
          # NozzleBox("Shadow Mario Turbo Nozzle Chase", 523871, Requirements([NozzleType.splasher, NozzleType.yoshi], shines=25)),
          parent_region=SmsRegionName.AIRSTRIP)