from .sms_region_helper import *


DELFINO_PLAZA: SmsRegion = SmsRegion(SmsRegionName.PLAZA,
    [Requirements(location=SmsRegionName.AIRSTRIP + " - Delfino Airstrip Dilemma")],
    shines=[Shine("Shine Sprite in the Sand", [Requirements(HOVORSHI)]),
        Shine("Clean the West Bell", [Requirements(ANY_SPLASHER)]),
        Shine("Super Slide", [Requirements(ROCKET_OR_HOVER_OR_YOSHI)]),
        Shine("Turbo Dash!", [Requirements([[NozzleType.turbo]])]),
        Shine("Lighthouse Roof", [Requirements([[NozzleType.rocket]])]),
        Shine("Clean the East Bell", [Requirements(ROCKET_AND_SPLASHER)]),
        Shine("Shine Gate", [Requirements(ROCKET_AND_SPLASHER)]),
        Shine("Lily Pad Ride", [Requirements(ALL_SPLASHER)]),
        Shine("Turbo Track", [Requirements([[NozzleType.turbo]])]),
        Shine("Red Coin Field", [Requirements(ROCKET_OR_HOVER_AND_SPRAY)]),

        Shine("Pachinko Game", [Requirements([[NozzleType.hover, NozzleType.rocket]]),
            Requirements([[NozzleType.hover]], shines=3),
            Requirements([[NozzleType.hover]], skip_forward=True)]),
        Shine("The Gold Bird", [Requirements(SPROVER_OR_YOSHI, shines=10),
            Requirements(SPROVER_OR_YOSHI, skip_forward=True)]),
        Shine("Boxing Clever 1", [Requirements(ANY_SPLASHER),
            Requirements(skip_forward=True)]),
        Shine("Boxing Clever 2", [Requirements(ANY_SPLASHER),
            Requirements(skip_forward=True)]),
        Shine("Chuckster", [Requirements(ANY_SPLASHER),
            Requirements(skip_forward=True)]),
        Shine("100 Coins", [Requirements(ROCKET_OR_HOVER),
            Requirements(skip_forward=True)], hundred=True)],

    blue_coins=[BlueCoin("Turbo Pillar", [Requirements([[NozzleType.turbo]])]),
          BlueCoin("Burning Pianta", [Requirements(ANY_SPLASHER)]),
          BlueCoin("Shine Gate M", [Requirements(ANY_SPLASHER)]),
          BlueCoin("Tower M", [Requirements(ANY_SPLASHER)]),
          BlueCoin("Chuckster Room M", [Requirements(ANY_SPLASHER)]),
          BlueCoin("Sea Sewer"),
          BlueCoin("Tower Yellow Goo", [Requirements([[NozzleType.yoshi]])]),
          BlueCoin("Jail Cell"),
          BlueCoin("Police Station Yellow Goo", [Requirements([[NozzleType.yoshi]])]),
          BlueCoin("Shine Gate Sewer"),
          BlueCoin("Canal Sewer"),
          BlueCoin("Blue Bird Near Sirena Pipe", [Requirements(SPRAY_OR_YOSHI)]),
          BlueCoin("Blue Bird Near Crate Guy", [Requirements(SPRAY_OR_YOSHI)]),
          BlueCoin("Statue X", [Requirements(ANY_SPLASHER)]),
          BlueCoin("Bell Tower X", [Requirements(ANY_SPLASHER)]),
          BlueCoin("Pineapple Basket", [Requirements(ANY_SPLASHER),
              Requirements(skip_forward=True)]),
          BlueCoin("Durian Basket", [Requirements(ANY_SPLASHER),
              Requirements(skip_forward=True)]),
          BlueCoin("Banana Basket", [Requirements(ANY_SPLASHER),
              Requirements(skip_forward=True)]),
          BlueCoin("Coconut Basket", [Requirements(ANY_SPLASHER)])],

          # NozzleBox("Shadow Mario Yoshi Egg Chase", 523911, Requirements([NozzleType.spray], location="Pinna Park - The Wilted Sunflowers")),
          # NozzleBox("Shadow Mario Rocket Nozzle Chase", 523870, Requirements([NozzleType.splasher, NozzleType.yoshi], shines=30)),
          # NozzleBox("Shadow Mario Turbo Nozzle Chase", 523871, Requirements([NozzleType.splasher, NozzleType.yoshi], shines=25)),
          parent_region=SmsRegionName.AIRSTRIP)